### ISSUE TITLE
[wish] Please drop dependency on IO::FDPass

### ISSUE THREAD

**Issue by Tux** [marioroy/mce-shared#1]
The module requires IO::FDPass, but all tests pass when that module is not installed, so it should either be dropped as requirement and made optional, or it should not be required at all.

Many users and system administrators will refuse to install any module maintained by Marc Lehmann, as his service level is too terrible to even consider using whatever he produces. Even if his modules make sense, people will look for alternatives in order to not have to communicate with Marc.

**Comment by marioroy** [comment]
Greetings,

Without IO::FDPass, there are restrictions for using Condvar, Handle, and Queue. These make socket handles and passed to the shared-manager via IO::FDPass if available. Without it, means that the user must construct these before other shared objects and afterwards start the shared-manager process manually. This is a pain and easily forgotten, causing confusion.

In other words, having IO::FDPass allows shared construction of Condvar, Handle, and Queue anytime and including after the shared-manager has been started. It elevates the user-experience in regards to sharing these three modules.

This all came about because a developer constructed a shared MCE::Shared->hash() before MCE::Shared->queue(). Once the shared-manager process is running, it is no longer possible to construct a shared Condvar, Handle, or Queue. Unless, IO::FDPass is available.

Maybe, I've made a mistake in creating Condvar, Handle, and Queue for MCE::Shared. Folks like the shared file capabilities. With IO::FDPass on the box, the following statements are allowed while the shared-manager process is running.

```
my $shared_hash = MCE::Shared->hash();      # shared-manager runs if not running
my $shared_cache = MCE::Shared->cache();

mce_open my $output_fh, ">>", "/path/to/file.log";   # ok, if IO::FDPass is available
mce_open my $input_fh, "<", "/path/to/file.log";
```

Are their alternatives that work on all the major platforms? Let me pass this wish list to a friend for extra help and guidance on this matter. I'm open to suggestions.

Kind regards, Mario.

**Comment by marioroy** [comment]
From talking to several folks, the opinion is that there is no reason to not use something on CPAN, especially when passing on many smoke machines. IO::FDPass is a great module, one that works as described on multiple platforms. In regards to MCE::Shared, there are more reasons in having IO::FDPass versus not. Trying to work around this seems counter productive IMHO.

The effort made to not have IO::FDPass was purely for running MCE::Shared with some restrictions under Cygwin where IO::FDPass isn't possible. That's a technical reason, not a political one.

I appreciate your feedback. Unfortunately, there are no alternatives at this time.

_"Be kind to one another"
     --Ellen DeGeneres_

**Comment by akotlar** [comment]
Not to reopen, but wanted to note that IO::FDPass appears to have trouble building on perl >= 5.28.0, at least I have had some issues, because of 2 dependencies, LWP::Simple, and File::Listing. This happened based off the Debian-based perl docker images.

Official reports:
https://www.cpantesters.org/distro/I/IO-FDPass.html?oncpan=1&distmat=1&version=1.2&grade=3

**Comment by marioroy** [comment]
Hi Alex. The dependency IO::FDPass seems to fail on arm-freebsd mainly. No issues with Linux from what I can tell. One can set an environment variable to not install IO::FDPass.
```
MCE_PREREQ_EXCLUDE_IO_FDPASS=1
```

**Comment by akotlar** [comment]
Still having issues with the official perl 5.28+ docker images, but it could definitely be a problem on my end! Thanks for the quick response and suggestion.
